### ISSUE TITLE
No slashed zero?

### ISSUE THREAD

**Issue by NetOpWibby** [githubnext/monaspace#18]
This is a glaring omission for an otherwise amazing set of typefaces.

**Comment by redactedscribe** [comment]
0 with a dot inside of it serves the same purpose.

**Comment by NetOpWibby** [comment]
My purpose is viewing a slash within a zero. Thus, your comment serves no purpose.

**Comment by NetOpWibby** [comment]
@redactedscribe My purpose is viewing a slash within a zero. Thus, your comment serves no purpose.

**Comment by stone-zeng** [comment]
It would be nice to provide an extra `ssXX` or `cvXX` feature to support slashed zero (and back-slashed zero, empty zero, etc).

**Comment by redactedscribe** [comment]
> @redactedscribe My purpose is viewing a slash within a zero. Thus, your comment serves no purpose.

0, O, and o are all sufficiently differentiated in the font. Sure, ask for an additional variant if you want, but I wouldn't say it's a glaring omission.

**Comment by kenny-kvibe** [comment]
+1
I got excited about this font and when I found out there's no slashed-zero stylistic set, I got kinda surprised.
I really hope you add it, because people who like slashed-zeros over dotted-zeros will not use it as is in my case.

My reason is that dotted-zeros can remind me of the "Theta" symbol (U+2609), which distracts me for a very small amount of time and I'd check its unicode if I was unsure, because the dotted-zero symbol has too many meanings to be just zero (for me).
And my reasoning of the slashed-zero is that it can remind me of an "Empty Set" symbol (U+2205), but if reminded it's not distracting at all because it has the meaning of zero in itself.

I'd like to know if you're planning of adding it?

Good reference fonts with the slashed-zero stylistic set:
SF Mono, ArrowType, Droid Sans, Consolas, Monospace

**Comment by idan** [comment]
#273  v1.2 added `cv01` for control of zeroes

**Comment by zakora** [comment]
Hello, thanks for the wonderful set of fonts!

I tested v1.200 and while I found ´cv01´ to switch from dotted- to undotted-zero, I didn't find a way to get a slashed-zero.

Is the slashed-zero available in v1.2? If not, would it make sense to re-open this issue?

**Comment by ScottESanDiego** [comment]
@zakora , set `cv01` to `2` and you get a slashed zero.

**Comment by jham** [comment]
The `cv01` support doesn't appear to work in the frozen versions of 1.2, at least in Neon where I tried it.

**Comment by jham** [comment]
The `cv01=2` code doesn't work in VS Code with the Var font, too. I'll open new issues for both.

**Comment by ScottESanDiego** [comment]
> The `cv01` support doesn't appear to work in the frozen versions of 1.2, at least in Neon where I tried it.

Works for me with 1.2 in Windows Terminal, using Neon.

![image](https://github.com/user-attachments/assets/518258cc-486f-414c-a648-190fb73d3130)
