### ISSUE TITLE
Nerd Fonts - Please - When? 🙏 

### ISSUE THREAD

**Issue by fschlegelone** [githubnext/monaspace#188]
Hey, I'm confused why there is no Nerd Font for monaspace, that would be awesome!

It's already asked in this thread: https://github.com/githubnext/monaspace/issues/24

But it happened nothing since then :(

**Comment by RaccoonBoryvitter** [comment]
The benefits of Nerd Fonts allow you to generate the font by yourself, so it should be pretty easy.

Well, not in every case, maybe there are some cases that require more work to do. But don't worry, such things have already been done for you. You can check [this link](https://github.com/ryanoasis/nerd-fonts/pull/1405) from the Nerd Fonts repository.

But let me ask you one question: do you mean you need stylized icons and other stuff specifically for the font? Because I hope I understood your question right as you meant.

**Comment by fschlegelone** [comment]
@RaccoonBoryvitter exactly :)
